#!/bin/bash

if [ -z "$1" ]; then
    echo "Debe especificar una carpeta como argumento"
    exit 1
fi

if [ -z "$(grep 'Nmap scan report' "$1"/*)" ]; then
    echo "No se encontraron IPs activas"
else
    grep -hoP '\(\K\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' "$1"/* | sort -u | xargs -I{} basename {}
fi
